[package]
name = "maxwell-the-cat"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = { version = "0.36", features = ["simple_window_builder"] }
image = { version = "0.25.5", default-features = false, features = ["jpeg", "png"] }
rodio = "0.20.1"
stringreader = "0.1.1"
