name: Linux Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.toml"
      - "shaders/**"
      - "models/**"
      - "textures/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.toml"
      - "shaders/**"
      - "models/**"
      - "textures/**"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install ALSA development libraries
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev  
    - name: Build
      run: cargo build --verbose --release
    - name: Upload build
      uses: actions/upload-artifact@v4.4.3
      with:
        path: ${{github.workspace}}/target/release/maxwell-the-cat
